@baseUrl = http://localhost:3000

### Listar todos os projetos
GET {{baseUrl}}/projetos/

### Listar apenas um projeto
GET {{baseUrl}}/projetos/25

### Criar um projeto
POST {{baseUrl}}/projetos/
Content-Type: application/json

{
    "nome": "Projeto para ser atualizado"
    ,"criadoPorId": 1
    ,"gestorId" : 15
    ,"categoria": "RPA"
    ,"status": "Em andamento"
    ,"dataInicio": "2026-12-31"
    ,"dataTermino": "2027-12-31"
    ,"dataTermino": "2027-12-31"
    ,"orcamento": "1000.00"
    ,"ganhoPar": "12.12"
    ,"prioridade": true
    ,"tarefas": [
        {
            "ordem": 1,
            "nome": "1 Tarefa de projeto de prioridade",
            "concluido": false,
            "status": "Concluída"
        },
        {
            "ordem": 2,
            "nome": "2 Tarefa de projeto de prioridade",
            "concluido": true
        },
        {
            "ordem": 3,
            "nome": "3 Tarefa de projeto de prioridade",
            "concluido": false
        }
    ]
}
### Atualizar um projeto
PATCH {{baseUrl}}/projetos/30
Content-Type: application/json

{
    "nome": "10000 PROJETO COM NOME ATUALIZADO",
    "orcamento": "555.10",
    "ganhoPar": "555,00",
    "criadoPorId": 4,
    "atualizadoPorId": 4,
    "gestorId": 15,
    "categoria": "RPA",
    "tarefas": [
    {
        "id": 99,
        "nome": "3 NOVA Tarefa de projeto de prioridade",
        "ordem": 21,
        "dataInicio": null,
        "dataTermino": null,
        "concluido": false,
        "status": "Em andamento"
    }
    ]
}
### Apagar um projeto
DELETE {{baseUrl}}/projetos/21





# ------------------------------------------------------------------------------------------------------------------------------------------
### Listar todos os usuarios
GET {{baseUrl}}/usuarios/

### Listar todos os gestores
GET {{baseUrl}}/usuarios/gestores

### Listar um usuario
GET {{baseUrl}}/usuarios/3

### Criar um usuario
POST {{baseUrl}}/usuarios/
Content-Type: application/json

{
    "nome": "Thiago Roberto Andrade Aguiar",
    "email": "roberto.aguiar@grendene.com.br",
    "gestorId": 4
    
}

### Atualizar um usuario
PATCH {{baseUrl}}/usuarios/10
Content-Type: application/json

{
    "gestorId": 100
}

### Apagar um usuario
DELETE {{baseUrl}}/usuarios/14





# ------------------------------------------------------------------------------------------------------------------------------------------
### Listar historico
GET {{baseUrl}}/usuarios/

### Listar todos os gestores
GET {{baseUrl}}/usuarios/gestores

### Listar um usuario
GET {{baseUrl}}/usuarios/3

### Criar um usuario
POST {{baseUrl}}/usuarios/
Content-Type: application/json

{
    "nome": "Thiago Roberto Andrade Aguiar",
    "email": "roberto.aguiar@grendene.com.br",
    "gestorId": 4
    
}

### Atualizar um usuario
PATCH {{baseUrl}}/usuarios/10
Content-Type: application/json

{
    "gestorId": 100
}

### Apagar um usuario
DELETE {{baseUrl}}/usuarios/14