@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os usuarios
GET {{baseUrl}}/users/
### Lista apenas um usuario
GET {{baseUrl}}/users/1/
### Cria um usuario
POST {{baseUrl}}/users/
Content-Type: application/json

{
    "nome": "Ana Souza",
    "fabrica": "Fábrica 1",
    "filial": "Farroupilha",
    "mail": "ana.souza@email.com"
}
### Atualiza um usuario
PATCH {{baseUrl}}/users/2
Content-Type: application/json

{
    "admin": true
}
### Apaga um usuario
DELETE {{baseUrl}}/users/5/




# Filiais
### Lista todas filiais
GET {{baseUrl}}/branch/
### Lista apenas uma filial
GET {{baseUrl}}/branch/3/
### Cria uma filial
POST {{baseUrl}}/branch/
Content-Type: application/json

{
    "name": "Farroupilha"
}
### Atualiza uma filial
PATCH {{baseUrl}}/branch/8
Content-Type: application/json

{
    "name": "Sobral"
}
### Apaga uma filial
DELETE {{baseUrl}}/branch/9